server:
  port: 8080

#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/WebsiteDemo
#    driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    username: fit5120
    password: 5122Ta05!
    url: jdbc:mysql://calendar.mysql.database.azure.com:3306/websitev1
    driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
      static-path-pattern: /**
       classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#spring:
#  logging.level.org.springframework.jdbc.core=DEBUG
#
#  spring.datasource.url=jdbc:sqlserver:jdbc:sqlserver://fit5120calendar.database.windows.net:1433;database=calendardb;user=fit5120@fit5120calendar;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#  spring.datasource.username=fit5120
#  spring.datasource.password=5122Ta05!
#
#  spring.datasource.initialization-mode=always
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.websitedemo
#showSql
logging:
  level:
    com:
      example:
        mapper : debug
thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  encoding: utf-8
  mode: html5
  servlet:
  content-type: text/html